import Link from "next/link"
import { ArrowRightIcon } from "lucide-react"

import { PageHeader } from "@/components/docs/page-header"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { docsConfig } from "@/config/docs"

export default function DocsIntroPage() {
  const components = docsConfig.sidebarNav.find(
    (g) => g.title === "Components"
  )?.items ?? []

  return (
    <div className="mx-auto max-w-3xl space-y-8">
      <PageHeader
        title="Introduction"
        description="A documentation playground for components generated by the shadcn-ui-design skill. Each component is sourced from a Figma node and mapped to design tokens defined in DESIGN.md."
      />

      <div className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight">How it works</h2>
        <ul className="ml-6 list-disc space-y-2 text-sm text-muted-foreground leading-6">
          <li>
            Components live under{" "}
            <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-xs text-foreground">
              components/examples/
            </code>
            .
          </li>
          <li>
            Sidebar navigation is driven by{" "}
            <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-xs text-foreground">
              config/docs.ts
            </code>
            . Add a new entry there to surface a new component page.
          </li>
          <li>
            Each component page uses the{" "}
            <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-xs text-foreground">
              ComponentPreview
            </code>{" "}
            wrapper to show a live preview alongside its source code.
          </li>
        </ul>
      </div>

      <Separator />

      <div className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight">Components</h2>
        <div className="grid gap-3 sm:grid-cols-2">
          {components.map((item) => (
            <Button
              key={item.href}
              variant="outline"
              size="lg"
              className="h-auto justify-between p-4"
              nativeButton={false}
              render={<Link href={item.href} />}
            >
              <span className="text-base font-medium">{item.title}</span>
              <ArrowRightIcon />
            </Button>
          ))}
        </div>
      </div>
    </div>
  )
}
